name: sarkari_result
description: "Sarkari Result Jobs list simplified"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  dynamic_color: ^1.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  html: ^0.15.5
  http: ^1.2.2
  intl: ^0.20.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  flutter_launcher_icons: ^0.14.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/sarkari_result_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/sarkari_result_icon.png"

flutter:
  uses-material-design: true
